development:
  adapter: postgresql
  encoding: unicode
  database: job_board_development
  pool: 5
  username: scotthughes
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: job_board_test
  pool: 5
  username: scotthughes
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: job-board_production
#   pool: 5
#   username: job-board
#   password:
